version: '3.6'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
      - './script.sql:/docker-entrypoint-initdb.d/script.sql'
      - '../data/customers.csv:/data/customers.csv'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypass
      - MARIADB_DATABASE=hameos
      - MARIADB_ROOT_PASSWORD=myrootpass
    ports:
      - '127.0.0.1:3306:3306'
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      - DATABASE_HOST=mariadb
volumes:
  mariadb_data:
    driver: local

